# Generated by Django 6.0.3 on 2026-03-25 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticion', models.PositiveSmallIntegerField()),
                ('peso_lastre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rpe', models.PositiveSmallIntegerField()),
                ('rir', models.PositiveSmallIntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.ejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.sesion')),
            ],
        ),
    ]
